import { saveAs } from 'file-saver';
import { ProjectPlan } from './openai';
import { ProjectRequirementsData } from '@/components/planner/PlannerFlow';

// Generate a formatted text document instead of PDF for simplicity
export const generatePDF = async (plan: ProjectPlan, projectData: ProjectRequirementsData) => {
  try {
    const content = `
═══════════════════════════════════════════════════════════════
                    ${plan.project_overview.name.toUpperCase()}
                       CUSTOM PROJECT PLAN
                    Generated by Inowix • ${new Date().toLocaleDateString()}
═══════════════════════════════════════════════════════════════

Contact: ${projectData.email}
${projectData.phone ? `Phone: ${projectData.phone}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 PROJECT OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Project Type: ${plan.project_overview.type}

Description:
${plan.project_overview.description}

Target Audience:
${plan.project_overview.target_audience}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⏰ PROJECT TIMELINE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Duration: ${plan.timeline.total_duration}

${plan.timeline.phases.map((phase, index) => `
Phase ${index + 1}: ${phase.name} (${phase.duration})
${phase.description}
Deliverables: ${phase.deliverables.join(', ')}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💰 BUDGET ESTIMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Estimated Cost: ${plan.budget_estimation.total_estimated_cost}

Cost Breakdown:
${plan.budget_estimation.cost_breakdown.map(item => `
• ${item.category}: ${item.cost}
  ${item.description}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛠️ TECHNOLOGY STACK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${Object.entries(plan.technology_stack).map(([category, technologies]) => `
${category.charAt(0).toUpperCase() + category.slice(1).replace('_', ' ')}:
${technologies.map(tech => `• ${tech}`).join('\n')}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✨ KEY FEATURES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${plan.features.map((feature, index) => `
${index + 1}. ${feature.name}
   Priority: ${feature.priority} | Complexity: ${feature.complexity}
   Estimated Time: ${feature.estimated_hours}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️ RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${plan.risk_assessment.map((risk, index) => `
${index + 1}. ${risk.risk}
   Probability: ${risk.probability} | Impact: ${risk.impact}
   Mitigation: ${risk.mitigation}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💡 EXPERT RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${Object.entries(plan.recommendations).map(([key, value]) => `
${key.charAt(0).toUpperCase() + key.slice(1).replace('_', ' ')}:
${value}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚀 NEXT STEPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${plan.next_steps.map((step, index) => `${index + 1}. ${step}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Ready to bring your vision to life?

📧 Email: info@inowix.in
📱 Phone: +91 6283075131
🌐 Website: www.inowix.in

Built with ❤️ by Inowix - Your Digital Dreams, Our Reality

    `;
    
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const fileName = `${plan.project_overview.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_project_plan.txt`;
    saveAs(blob, fileName);
  } catch (error) {
    console.error('Plan generation error:', error);
    throw new Error('Failed to generate plan document');
  }
};