import { saveAs } from 'file-saver';
import { ProjectPlan } from '../types/plan';
import { ProjectRequirementsData } from '@/components/planner/PlannerFlow';

// Generate a formatted text document instead of PDF for simplicity
export const generatePDF = async (plan: ProjectPlan, projectData: ProjectRequirementsData) => {
  try {
    const content = `
═══════════════════════════════════════════════════════════════
                    ${plan.title.toUpperCase()}
                       CUSTOM PROJECT PLAN
                    Generated by Inowix • ${new Date().toLocaleDateString()}
═══════════════════════════════════════════════════════════════

Contact: ${projectData.email}
${projectData.phone ? `Phone: ${projectData.phone}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 PROJECT OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Description:
${plan.description}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⏰ PROJECT TIMELINE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Timeline: ${plan.timeline}

${plan.phases.map((phase, index) => `
Phase ${index + 1}: ${phase.name} (${phase.duration})
Tasks: ${phase.tasks.join(', ')}
Deliverables: ${phase.deliverables.join(', ')}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💰 BUDGET ESTIMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Budget Range: ${plan.budget.range}

Cost Breakdown:
${plan.budget.breakdown.map(item => `
• ${item.category}: ${item.amount}
  ${item.description}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛠️ TECHNOLOGY STACK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Technology recommendations and tools will be detailed during project kickoff.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✨ KEY FEATURES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Project features and requirements will be refined during detailed planning phase.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️ RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${plan.risks.map((risk, index) => `
${index + 1}. ${risk}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💡 EXPERT RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${plan.recommendations.map((rec, index) => `
${index + 1}. ${rec}
`).join('')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚀 NEXT STEPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Review and approve this project plan\n2. Finalize project scope and requirements\n3. Set up project timeline and milestones\n4. Begin project kickoff phase

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Ready to bring your vision to life?

📧 Email: info@inowix.in
📱 Phone: +91 6283075131
🌐 Website: www.inowix.in

Built with ❤️ by Inowix - Your Digital Dreams, Our Reality

    `;
    
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const fileName = `${plan.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_project_plan.txt`;
    saveAs(blob, fileName);
  } catch (error) {
    console.error('Plan generation error:', error);
    throw new Error('Failed to generate plan document');
  }
};